import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import { SidebarItemConfig } from "@docusaurus/plugin-content-docs/src/sidebars/types.js";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    // 설정
    {
      type: "category",
      label: "설정",
      collapsible: true,
      collapsed: true,
      items: [
        "setup/setup-overview",
        "setup/linux",
        "setup/mac",
        "setup/windows",
        "setup/raspberry-pi",
        "setup/network",
        "setup/additional-components",
        "setup/enterprise",
        "setup/uninstall",
      ],
    },
    // 시작하기
    {
      type: "category",
      label: "시작하기",
      collapsible: true,
      collapsed: true,
      items: [
        "getstarted/getting-started",
        "getstarted/introvideos",
        "getstarted/tips-and-tricks",
        "getstarted/userinterface",
        "getstarted/educators-and-students",
      ],
    },
    // 유저 가이드
    {
      type: "category",
      label: "유저 가이드",
      collapsible: true,
      collapsed: true,
      items: [
        "editor/codebasics",
        "editor/extension-marketplace",
        "editor/intellisense",
        "editor/editingevolved",
        "editor/refactoring",
        "editor/debugging",
        "editor/testing",
        "editor/vscode-web",
        "editor/tasks",
        "editor/profiles",
        "editor/settings-sync",
        "editor/userdefinedsnippets",
        "editor/emmet",
        "editor/command-line",
        "editor/workspaces/workspaces",
        "editor/workspaces/workspace-trust",
        "editor/workspaces/multi-root-workspaces",
        "editor/accessibility",
        "editor/voice",
        "editor/custom-layout",
        "editor/port-forwarding",
      ],
    },
    // 소스 관리
    {
      type: "category",
      label: "소스 관리",
      collapsible: true,
      collapsed: true,
      items: [
        "sourcecontrol/overview",
        "sourcecontrol/intro-to-git",
        "sourcecontrol/github",
        "sourcecontrol/faq",
      ],
    },
    // 터미널
    {
      type: "category",
      label: "터미널",
      collapsible: true,
      collapsed: true,
      items: [
        "terminal/getting-started",
        "terminal/basics",
        "terminal/profiles",
        "terminal/shell-integration",
        "terminal/appearance",
        "terminal/advanced",
      ],
    },
    // GitHub Copilot
    {
      type: "category",
      label: "GitHub Copilot",
      collapsible: true,
      collapsed: true,
      items: [
        "copilot/overview",
        "copilot/copilot-vscode-features",
        "copilot/setup",
        "copilot/getting-started",
        "copilot/ai-powered-suggestions",
        "copilot/copilot-chat",
        "copilot/getting-started-chat",
        "copilot/copilot-edits",
        "copilot/prompt-crafting",
        "copilot/workspace-context",
        "copilot/copilot-customization",
        "copilot/copilot-extensibility-overview",
        "copilot/copilot-settings",
        "copilot/faq",
      ],
    },
    // 프로그래밍 언어
    {
      type: "category",
      label: "프로그래밍 언어",
      collapsible: true,
      collapsed: true,
      items: [
        "languages/javascript",
        "languages/json",
        "languages/html",
        "languages/css",
        "languages/typescript",
        "languages/markdown",
        "languages/powershell",
        "languages/cpp",
        "languages/java",
        "languages/php",
        "languages/python",
        "languages/julia",
        "languages/r",
        "languages/ruby",
        "languages/rust",
        "languages/go",
        "languages/tsql",
        "languages/csharp",
        "languages/dotnet",
        "languages/polyglot",
      ],
    },
    // Node.js / JavaScript
    {
      type: "category",
      label: "Node.js / JavaScript",
      collapsible: true,
      collapsed: true,
      items: [
        "nodejs/working-with-javascript",
        "nodejs/nodejs-tutorial",
        "nodejs/nodejs-debugging",
        "nodejs/nodejs-deployment",
        "nodejs/browser-debugging",
        "nodejs/angular-tutorial",
        "nodejs/reactjs-tutorial",
        "nodejs/vuejs-tutorial",
        "nodejs/debugging-recipes",
        "nodejs/profiling",
        "nodejs/extensions",
      ],
    },
    // TypeScript
    {
      type: "category",
      label: "TypeScript",
      collapsible: true,
      collapsed: true,
      items: [
        "typescript/typescript-tutorial",
        "typescript/typescript-compiling",
        "typescript/typescript-editing",
        "typescript/typescript-refactoring",
        "typescript/typescript-debugging",
      ],
    },
    // Python
    {
      type: "category",
      label: "Python",
      collapsible: true,
      collapsed: true,
      items: [
        "python/python-quick-start",
        "python/python-tutorial",
        "python/run",
        "python/editing",
        "python/linting",
        "python/formatting",
        "python/debugging",
        "python/environments",
        "python/testing",
        "python/jupyter-support-py",
        "python/tutorial-django",
        "python/tutorial-fastapi",
        "python/tutorial-flask",
        "python/tutorial-create-containers",
        "python/python-on-azure",
        "python/python-web",
        "python/settings-reference",
      ],
    },
    // Java
    {
      type: "category",
      label: "Java",
      collapsible: true,
      collapsed: true,
      items: [
        "java/java-tutorial",
        "java/java-editing",
        "java/java-refactoring",
        "java/java-linting",
        "java/java-project",
        "java/java-build",
        "java/java-debugging",
        "java/java-testing",
        "java/java-spring-boot",
        "java/java-tomcat-jetty",
        "java/java-on-azure",
        "java/java-gui",
        "java/extensions",
        "java/java-faq",
      ],
    },
    // C++
    {
      type: "category",
      label: "C++",
      collapsible: true,
      collapsed: true,
      items: [
        "cpp/introvideos-cpp",
        "cpp/config-linux",
        "cpp/config-mingw",
        "cpp/config-wsl",
        "cpp/config-clang-mac",
        "cpp/config-msvc",
        "cpp/build-with-cmake",
        "cpp/cmake-linux",
        "cpp/cmake-quickstart",
        "cpp/cpp-ide",
        "cpp/cpp-debug",
        "cpp/cpp-refactoring",
        "cpp/launch-json-reference",
        "cpp/customize-default-settings-cpp",
        "cpp/configure-intellisense",
        "cpp/configure-intellisense-crosscompilation",
        "cpp/faq-cpp",
      ],
    },
    // C#
    {
      type: "category",
      label: "C#",
      collapsible: true,
      collapsed: true,
      items: [
        "csharp/introvideos-csharp",
        "csharp/get-started",
        "csharp/navigate-edit",
        "csharp/intellicode",
        "csharp/refactoring",
        "csharp/formatting-linting",
        "csharp/project-management",
        "csharp/build-tools",
        "csharp/package-management",
        "csharp/debugging",
        "csharp/testing",
        "csharp/cs-dev-kit-faq",
      ],
    },
    // Docker
    {
      type: "category",
      label: "DOCKER",
      collapsible: true,
      collapsed: true,
      items: [
        "containers/overview",
        "containers/debug-node",
        "containers/debug-python",
        "containers/quickstart-aspnet-core",
        "containers/debug-common",
        "containers/docker-compose",
        "containers/quickstart-container-registries",
        "containers/app-service",
        "containers/choosing-dev-environment",
        "containers/reference",
        "containers/bridge-to-kubernetes",
        "containers/troubleshooting",
      ],
    },
    // 데이터 과학
    {
      type: "category",
      label: "데이터 과학",
      collapsible: true,
      collapsed: true,
      items: [
        "datascience/overview",
        "datascience/jupyter-notebooks",
        "datascience/data-science-tutorial",
        "datascience/python-interactive",
        "datascience/data-wrangler-quick-start",
        "datascience/data-wrangler",
        "datascience/pytorch-support",
        "datascience/azure-machine-learning",
        "datascience/jupyter-kernel-management",
        "datascience/notebooks-web",
      ],
    },
    // Azure
    {
      type: "category",
      label: "AZURE",
      collapsible: true,
      collapsed: true,
      items: [
        "azure/overview",
        "azure/gettingstarted",
        "azure/deployment",
        "azure/docker",
        "azure/kubernetes",
        "azure/kubernetes",
        "azure/mongodb",
        "azure/remote-debugging",
      ],
    },
    // 원격 개발
    {
      type: "category",
      label: "원격 개발",
      collapsible: true,
      collapsed: true,
      items: [
        "remote/remote-overview",
        "remote/ssh",
        "remote/dev-containers",
        "remote/wsl",
        "remote/codespaces",
        "remote/vscode-server",
        "remote/tunnels",
        "remote/ssh-tutorial",
        "remote/wsl-tutorial",
        "remote/troubleshooting",
        "remote/faq",
      ],
    },
    // Dev 컨테이너
    {
      type: "category",
      label: "Dev 컨테이너",
      collapsible: true,
      collapsed: true,
      items: [
        "devcontainers/containers",
        "devcontainers/tutorial",
        "devcontainers/attach-container",
        "devcontainers/create-dev-container",
        "devcontainers/containers-advanced",
        "devcontainers/devcontainerjson-reference",
        "devcontainers/devcontainer-cli",
        "devcontainers/tips-and-tricks",
        "devcontainers/faq",
      ],
    },
  ],
};

export default sidebars;
